# Day 2 -- Python for Researchers

## Today's Goals:
   * Use the pandas library
   * Understand what a dataframe and series are
   * Learn how to execute basic data cleaning
   * Learn some key functions for data analysis

**Introduction to Pandas**

Pandas is the industry standard data analysis library. It lets us convert raw datasets (typically a .csv file) into something called a *dataframe*. A dataframe looks like a spreadsheet, but is actually optimized to allow you to handle large datasets quickly and efficiently. We can use pandas to clean, analyze, and even visualize our data. 

In pandas you can work with two kinds of objects -- a dataframe, or a 2D array (something with rows and columns) or a series, a 1D array (or just a  singular column). Both of these objects comes with different built-in functions that we will explore throughout today's lesson. 

Pandas is a really powerful tool for researchers. Oftentimes, the way you really learn to master it is by looking at examples and reading documentation. They have a ["10 Minutes to Pandas"](https://pandas.pydata.org/docs/user_guide/10min.html) guide we recommend you return to after this week. You can also reference the [official documentation](https://pandas.pydata.org/docs/reference/frame.html) or the more simple, but less detailed, [w3schools documentation](https://www.w3schools.com/python/pandas/pandas_dataframes.asp).

#### Section 1: Our first dataset 

To start our exploration of pandas, we're going to use a Film Permits dataset from the [NYC Open Data site](https://data.cityofnewyork.us/City-Government/Film-Permits/tg4x-b46p/about_data). That dataset is already in our Day 3 folder. Please note: when you gather a dataset online, it typically comes with it's own internal logic -- especially goverment datasets -- so you will want to study any documentation they provide to better undersatnd your data. 

In order to use pandas, you always have to import it. The common way to do this is to *import pandas as pd* -- pd just is a shorter amout of letters to type in. 

We are using a csv file, that stands for "comma separated values" and is an agnostic file type. You could also load an excel spreadsheet with the function pd.read_excel('file.xlsx'). Learn more about the different types of files you can use pandas with in the [input/output documentation](https://pandas.pydata.org/docs/reference/io.html).

To create your dataframe, you run the code below. Our dataframe is being stored in the variable permits_df.

In [ ]:
import pandas as pd
permits_df = pd.read_csv("Film_Permits_20250518.csv")

#Take a second to study the output, what can we learn from it?
permits_df

,EventID,EventType,StartDateTime,EndDateTime,EnteredOn,EventAgency,ParkingHeld,Borough,CommunityBoard(s),PolicePrecinct(s),Category,SubCategoryName,Country,ZipCode(s)
0,753784,Theater Load in and Load Outs,12/24/2023 12:01:00 AM,12/31/2023 11:59:00 PM,12/18/2023 12:59:21 PM,Mayor's Office of Media & Entertainment,WEST 62 STREET between COLUMBUS AVENUE and A...,Manhattan,7,20,Theater,Theater,United States of America,10023
1,752706,Shooting Permit,12/13/2023 06:00:00 AM,12/13/2023 08:00:00 PM,12/06/2023 09:01:38 AM,Mayor's Office of Media & Entertainment,HUDSON STREET between MORTON STREET and BARROW...,Manhattan,"1, 2, 3","5, 6, 7, 84, 90",Film,Feature,United States of America,"10002, 10014, 10038, 11201, 11211"
2,753230,Shooting Permit,12/18/2023 07:00:00 AM,12/18/2023 11:59:00 PM,12/12/2023 10:09:19 AM,Mayor's Office of Media & Entertainment,ROSE FEISS BOULEVARD between EAST 139 STREET ...,Bronx,1,40,Television,Episodic series,United States of America,10454
3,752951,Shooting Permit,12/14/2023 07:00:00 AM,12/14/2023 09:00:00 PM,12/08/2023 09:29:50 AM,Mayor's Office of Media & Entertainment,ATLANTIC AVENUE between WASHINGTON AVENUE and ...,Brooklyn,8,77,Television,Episodic series,United States of America,11238
4,752181,Shooting Permit,12/13/2023 06:00:00 AM,12/13/2023 11:59:00 PM,12/01/2023 09:38:19 AM,Mayor's Office of Media & Entertainment,GRAND AVENUE between 64 STREET and FLUSHING AV...,Queens,"1, 5","104, 94",Television,Episodic series,United States of America,"11222, 11378"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11576,835577,Shooting Permit,02/15/2025 12:00:00 AM,02/15/2025 01:00:00 PM,02/14/2025 09:47:11 AM,Mayor's Office of Media & Entertainment,WEST 48 STREET between 6 AVENUE and 7 AVENUE,Manhattan,5,18,Television,News,United States of America,"10036, 10105"
11577,834355,Theater Load in and Load Outs,02/15/2025 12:01:00 AM,02/15/2025 11:59:00 PM,02/04/2025 01:57:53 PM,Mayor's Office of Media & Entertainment,EAST 11 STREET between 3 AVENUE and 4 AVENUE...,Manhattan,"11, 3","23, 9",Theater,Theater,United States of America,"10003, 10029"
11578,834236,Theater Load in and Load Outs,02/15/2025 12:01:00 AM,02/16/2025 06:00:00 AM,02/03/2025 04:23:45 PM,Mayor's Office of Media & Entertainment,DEKALB AVENUE between FLATBUSH AVENUE EXTENSIO...,Brooklyn,2,88,Theater,Theater,United States of America,11201
11579,834362,Theater Load in and Load Outs,02/16/2025 12:01:00 AM,02/17/2025 06:00:00 AM,02/04/2025 02:09:39 PM,Mayor's Office of Media & Entertainment,EAST 11 STREET between 3 AVENUE and 4 AVENUE...,Manhattan,"11, 3","23, 9",Theater,Theater,United States of America,"10003, 10029"
11580,835038,Shooting Permit,02/16/2025 06:00:00 AM,02/16/2025 10:00:00 PM,02/10/2025 03:05:07 PM,Mayor's Office of Media & Entertainment,EAST 136 STREET between BRUCKNER BOULEVARD an...,Bronx,1,40,Film,Short,United States of America,10454

**Learning about our dataset**

We're going to use four techniques to learn about our dataset:

  * info() -- tells you how many rows and columns there are; the names of each column; the different kinds of datatype contained in the columns; and how many non-null values there are in each column
  * head() -- shows by default the top five rows, you can add an optional parameter (a number) to show more
  * tail() -- same as head(), except it shows you the bottom rows
  * .dtypes -- tells you what each column's data type is

In [ ]:
permits_df.info()

In [ ]:
permits_df.head()

In [ ]:
permits_df.tail()

Note that there are seven datatypes in pandas, some of which correspond to the datatypes in Python:

* object (equivalent to a Python string - could be a combination of letters, numbers, and special characters)
* int64 (integer)
* float64 (floating number aka decimal)
* bool (Boolean, True/False values)
* datetime64 (date and time values)
* timedelta[ns] (differences between two values)
* category (finite list of text values, corresponds to categorical variables in statistics)

It's important to know what types of data you are manipulating, because they all come with unique abilities and limitations.

What kind of datatypes does our dataframe contain?

In [2]:
permits_df.dtypes

EventID               int64
EventType            object
StartDateTime        object
EndDateTime          object
EnteredOn            object
EventAgency          object
ParkingHeld          object
Borough              object
CommunityBoard(s)    object
PolicePrecinct(s)    object
Category             object
SubCategoryName      object
Country              object
ZipCode(s)           object
dtype: object

We can also access specific information in our dataframe. The most frequent way you will do this is to isolate a column. 

The preferred syntax for this is to use brackets and input the column name as strings. You can isolate only one at a time, 
or isolate multiple by writing them in a list.

In [ ]:
#isolating one column
permits_df["Borough"]

In [ ]:
#isolating multiple columns
permits_df[["EventID", "Borough", "Category"]]

If you want to isolate very specific information, you can use .iloc and .loc

 * You use .loc when dealing with column names (labels), e.g., below isolates the rows in the EventType column that are "Theater Load in and Load Outs"
 * You use .iloc when you want to index a specific row and column (iloc stands of “integer location”),
   e.g., below isolates the first five entries in the EventAgency column

In [ ]:
#example of loc

permits_df.loc[permits_df["EventType"] == "Theater Load in and Load Outs"]

In [8]:
#example of iloc

permits_df.iloc[:5, 5]

0    Mayor's Office of Media & Entertainment
1    Mayor's Office of Media & Entertainment
2    Mayor's Office of Media & Entertainment
3    Mayor's Office of Media & Entertainment
4    Mayor's Office of Media & Entertainment
Name: EventAgency, dtype: object

**Preparing our dataset for analysis**

Here's our research question: *How many of each film permit type was distributed in each borough?* Because this dataset was produced by NYC, it's pretty clean. We just want to drop the columns that don't help us answer our research question so that we can save memory. It's not a huge dataset, so this isn't necessary, but is useful to know how to do. 

Here are all our columns (I turned them into a list for easy reading).

In [ ]:
list(permits_df.columns)

We probably don't care about a number of those partiular columns, so let's drop them.

It's best practice to make a copy of your dataframe before you start changing it, so we'll start with that:

In [3]:
permits_df_copy = permits_df.copy()

Then we can drop several of those columns using drop(). Here's some info about what we're doing:
 * drop() elimates columns
 * You have to tell it what column names you want to drop, this can be passed as a list 
 * You also want to explicitly tell pandas that you are dropping columns using the columns keyword (alternative names: keyword argument, kwarg, parameter)
 * We are storing the changes in the same variable - this is called **reassigning**

I've dropped two columns below, try adding another column name to the list that we don't need!

In [4]:
#reassigning - or saving over - our permits_df_copy variable 
permits_df_copy = permits_df_copy.drop(columns=["CommunityBoard(s)", "PolicePrecinct(s)"])

**Doing the analysis**

We need to take the next four steps to answer our RQ:
  * isolate the two columns that have our information (EventType and Borough)
  * use value_counts() which helps us aggregate values in columns
  * convert this into it's own dataframe using reset_index()
  * sort the columns for easier viewing using sort_values()


Warning:
Each of these actions is CHANGING data! If you run them multiple times you may get errors. When in doubt, you can go back up to the previous cell and re-establish the permits_df_copy variable to start with a clean dataframe.

In [10]:
#isolate our two columns:

rq_df = permits_df_copy[["EventType", "Borough"]]
rq_df

                           EventType    Borough
0      Theater Load in and Load Outs  Manhattan
1                    Shooting Permit  Manhattan
2                    Shooting Permit      Bronx
3                    Shooting Permit   Brooklyn
4                    Shooting Permit     Queens
...                              ...        ...
11576                Shooting Permit  Manhattan
11577  Theater Load in and Load Outs  Manhattan
11578  Theater Load in and Load Outs   Brooklyn
11579  Theater Load in and Load Outs  Manhattan
11580                Shooting Permit      Bronx

[11581 rows x 2 columns]

In [11]:
#count the values
#this output LOOKS like it is a dataframe, but it's actually a series

rq_df = rq_df.value_counts()
rq_df

#You can always use the type() in Python if you are unsure about what kind of data you're dealing with 
#type(rq_df)

EventType                      Borough
Shooting Permit                Manhattan        3945
                               Brooklyn         3176
Theater Load in and Load Outs  Manhattan        1648
Shooting Permit                Queens           1535
Theater Load in and Load Outs  Brooklyn          560
Shooting Permit                Bronx             331
Rigging Permit                 Manhattan         132
                               Brooklyn           74
Shooting Permit                Staten Island      63
DCAS Prep/Shoot/Wrap Permit    Manhattan          50
Rigging Permit                 Queens             28
                               Bronx              17
DCAS Prep/Shoot/Wrap Permit    Bronx               6
                               Brooklyn            5
Theater Load in and Load Outs  Bronx               5
DCAS Prep/Shoot/Wrap Permit    Queens              3
Rigging Permit                 Staten Island       1
DCAS Prep/Shoot/Wrap Permit    Staten Island       1
Theater Load in and Load Outs  Queens              1
Name: count, dtype: int64

In [12]:
#reset the index to transform it into a dataframe

rq_df = rq_df.reset_index()
rq_df.columns = ["Event", "Borough", "Count"] #names columns
rq_df

                            Event        Borough  Count
0                 Shooting Permit      Manhattan   3945
1                 Shooting Permit       Brooklyn   3176
2   Theater Load in and Load Outs      Manhattan   1648
3                 Shooting Permit         Queens   1535
4   Theater Load in and Load Outs       Brooklyn    560
5                 Shooting Permit          Bronx    331
6                  Rigging Permit      Manhattan    132
7                  Rigging Permit       Brooklyn     74
8                 Shooting Permit  Staten Island     63
9     DCAS Prep/Shoot/Wrap Permit      Manhattan     50
10                 Rigging Permit         Queens     28
11                 Rigging Permit          Bronx     17
12    DCAS Prep/Shoot/Wrap Permit          Bronx      6
13    DCAS Prep/Shoot/Wrap Permit       Brooklyn      5
14  Theater Load in and Load Outs          Bronx      5
15    DCAS Prep/Shoot/Wrap Permit         Queens      3
16                 Rigging Permit  Staten Island      1
17    DCAS Prep/Shoot/Wrap Permit  Staten Island      1
18  Theater Load in and Load Outs         Queens      1

In [13]:
rq_df.sort_values("Event", inplace = True, ascending = False) 
rq_df

                            Event        Borough  Count
18  Theater Load in and Load Outs         Queens      1
2   Theater Load in and Load Outs      Manhattan   1648
14  Theater Load in and Load Outs          Bronx      5
4   Theater Load in and Load Outs       Brooklyn    560
8                 Shooting Permit  Staten Island     63
1                 Shooting Permit       Brooklyn   3176
0                 Shooting Permit      Manhattan   3945
5                 Shooting Permit          Bronx    331
3                 Shooting Permit         Queens   1535
7                  Rigging Permit       Brooklyn     74
6                  Rigging Permit      Manhattan    132
10                 Rigging Permit         Queens     28
11                 Rigging Permit          Bronx     17
16                 Rigging Permit  Staten Island      1
12    DCAS Prep/Shoot/Wrap Permit          Bronx      6
13    DCAS Prep/Shoot/Wrap Permit       Brooklyn      5
15    DCAS Prep/Shoot/Wrap Permit         Queens      3
17    DCAS Prep/Shoot/Wrap Permit  Staten Island      1
9     DCAS Prep/Shoot/Wrap Permit      Manhattan     50

It's your turn! 

Try to answer this research question: *Which borough distributed the most permits?*

The best way to think about how to answer that question is to consider:
  1. What information are you trying to access? 
  2. What rows or columns *have* that information?
  3. What tools do you have in the pandas library that can accomplish that task?

In [ ]:
#your answer

#### Section 2: Our Second Dataset 

You can find our second dataset [here](https://drive.google.com/file/d/1RgcK9VPCIxVMDZabQAJhWCp7z0LD_Im3/view?usp=sharing). It has information about the top 1000 ranking movies on IMDB. Please download that and bring it into your working directory.

Oftentimes online movie ratings have a recency bias -- that is, the more recently a movie was made, the more likely it is to have a high review because people have just seen it. That leads us to ask a few questions: *How many different years are represented in this dataset? Which years have the highest number of movies associated with them? And of those years, are most of them after 2000?*

In [14]:
import pandas as pd

film_df = pd.read_csv("imdb_top_1000.csv")
film_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

**Cleaning data three different ways**

There's actually an error in our dataset that is going to create an issue for us. Do you notice that the Release_Year column is an object datatype? You wouldn't expect that because it should *in theory* all be numbers. What I found is that one singular row has the string "PG" in it instead of a year.

In [15]:
#proof that we have one singular string in our Released_Year column

for i in film_df["Released_Year"].to_list():
    if i.isalpha():
        print(i)

PG

*Using loc[]*

I can use loc[] (which we learned above) to isolate this row because I know the value (pandas calls this a label). Remember: loc[] lets us access rows and columns by the label! This then shows me the index. I can then use the index to drop that row from my dataset.

In [16]:
film_df.loc[film_df["Released_Year"] == "PG"]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [ ]:
#notice that we only have 999 rows now compared to before!

film_df_copy = film_df.drop(966)
film_df_copy.info()

*Using isin()*

This looks for a list of values in the row, and if they ARE present, it drops them. Notice that we're isolating the appropriate column, using .isin() to pass a list of values (in this case, we only had one value!), and only keep the rows that do NOT have those values in them.

In [ ]:

film_df_copy_2 = film_df[film_df["Released_Year"].isin(["PG"]) == False]
#alternative line film_df_copy_2 = film_df[~film_df["Released_Year"].isin(["PG"])]
film_df_copy_2.info()

*Flexible solution with notna()*

There is an inherent limitation to the previous two solutions: if we have more than one row with alphabetical characters, and those are different, it becomes quite tedious! This is called *hard coding*, where you create a very inflexible bit of code that only works for one singluar situation. Generally, you want to build flexible code that can handle multiple situations. 

Thus, the better, and more flexible, method would be to simply drop the rows if they contained alphabetical characters. This produces the same effect as above, but would work with ANY row that contained alphabetical characters. 

Here's a breakdown:
  * We isolated the Released_Year column and try to convert each value to a number using to_numeric(). If that value cannot be converted, it becomes NaN. This means Not A Number and is pandas version of "None" or "Null"
  * the function notna() in pandas returns a True Boolean for any value that isn't NAN
  * this construction automatically keeps only the rows where notna() returned a True Boolean

In [ ]:
film_df = film_df[pd.to_numeric(film_df["Released_Year"], errors="coerce").notna()]
film_df.info()

Importantly, that column is STILL listed as an object datatype, we have to take the final step to convert it into an int64 datatype, no matter which of the three options above we chose to do.

In [ ]:
#resetting the column to be read as integers (numbers)
film_df = film_df.astype({"Released_Year": "int64"})

Now we can answer our RQ! It turns out that there are 100 years of movies represented in this dataset, but 17 out of the 20 top-rated movies come from after 2000. So I would definitely say it has a recency bias!

Below we use a concept called *boolean masking*. It's super useful in pandas!
  * It issentially is a way we can overlay (or mask) or data with boolean values. 
  * You just need to establish a condition, and when you pass that condition to your dataframe, it will automatically drop all of the False boolean values

In [ ]:
#creating new dataframe
year_aggregate = film_df["Released_Year"].value_counts()
year_aggregate = year_aggregate.reset_index()
year_aggregate.columns = ["Release Year", "Number of Movies"]

year_aggregate

In [ ]:
#isolate top 20
top_20 = year_aggregate.head(20)
top_20

In [101]:
#boolean masking
condition_1 = top_20["Release Year"] >= 2000
final_df = top_20[condition_1]
final_df.count()

Release Year        17
Number of Movies    17
dtype: int64

Now that we've done ALL that, let's also evaluate which release year has the highest rating on average to see if there's a bias that way. There doesn't seem to be one!

Here's what groupby() does:
  * It groups rows in a dataframe based on the values of one or more columns. In this case, we're grouping the release year column by the IMDB rating. 
  * Notice the syntax, we are grouping the rows in the Released_Year column and we're taking the mean (average) IMDB rating for each.

In [85]:
avg_rating = film_df.groupby("Released_Year")["IMDB_Rating"].mean()

In [ ]:
avg_rating_df = avg_rating.reset_index()
avg_rating_df.columns = ["Year", "Avg_Rating"]

avg_rating_df.sort_values("Avg_Rating", inplace = True, ascending = False) 
avg_rating_df.head(20)

If you understand this recency bias, you could isolate only the rows that come from before 2000 and do your analysis excluding more recent movies. We can use loc[] or boolean masking to do this, it accomplishes the same thing! Generally loc[] is the preferred method because it's more precise overall, but it's useful to know multiple means of doing something.

In [ ]:
film_df.loc[film_df["Released_Year"] < 2000]

In [ ]:
#You try to accomplish this with a Boolean mask!

We could similarly choose to only look at movies from a particular decade:

In [ ]:
column = film_df["Released_Year"]

film_df.loc[(column >= 1980) & (column <= 1989)]

#### Section 3: Your turn!

You are going to continue to use the IMDB dataset to answer the question *what is the average IMDB rating of the top 10 directors (by frequency) represented in the dataset?*

  To answer this:

  *   First, isolate the top 10 directors (as a hint: Alfred Hitchcock is number one)
  *   Like we did above, convert that information into a dataframe.
  *   Isolate the column with the directors in it and convert it into a list using [tolist()](https://www.geeksforgeeks.org/python-pandas-series-tolist/).
  *   I want you to adapt the syntax that we learned above to strip PG out of the dataframe. You want to create a new copy of the dataframe and strip all directors out of it except those in the list we just created.
  *   Finally, you can use groupby() to figure out what the average IMDB score is for those director's movies.

In [ ]:
#Your code here!